#!/bin/bash
while sleep 30; do
  touch test
  echo $(date +%m_%d%y-%H.%M.%S) > test
  git init > /dev/null
  git add . > /dev/null
  git commit -m "fake commit" > /dev/null
  #git remote add nk https://github.com/NoahKittleson/bash-test.git
  git push nk master > /dev/null
  echo "Fake commit pushed to git at" $(date +%m_%d%y-%H.%M.%S)
done
